global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'apps'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8080', 'host.docker.internal:8080', '192.168.0.187:8080','192.168.0.187:8081','192.168.0.187:8082','192.168.0.187:8083' ]